### ISSUE TITLE
Make testimonials avatar clickable links

### ISSUE THREAD

**Issue by zaiste** [polyconf/15.polyconf.com#4]

**Comment by matiangul** [comment]
Now I am in Berlin and I don't have my laptop with me. But when I come back I will take care of this this.

Ps If you want something from Berlin then ask me  :-)

**Comment by matiangul** [comment]
I am really sorry to say that, but I still cannot do this task :-/ I had to give my laptop for reparation today just after work.

**Comment by matiangul** [comment]
Is it suppose to look like it was on 14.polyconf.com website - move testimonials to pop-up? Or to link them to twitter / ... ?
